### ISSUE TITLE
For discussion: software install opening a terminal copy

### ISSUE THREAD

**Issue by SteveAmor** [raspberrypilearning/using-scratch2#3]
PR #2 has the following copy in software.md :

To install the software you need, run the following commands in a terminal window (press **Ctrl + Alt + t**):

Which I got from here:

https://www.raspberrypi.org/learning/graphing-the-weather/requirements/software/

However, it doesn't fit very well on the page as the **t**): is on a second line.

I also noticed that other resources simply say:

To install the software you need, run the following commands in a terminal window:

Should the above be the standard copy?  Or place the part about opening a terminal window on the next line?

**Comment by lawsie** [comment]
PR2 is now merged. I think there are a variety of different "run this in a terminal"-esque lines in different resources. Anyway, this went through copy edit and if our copy editors are happy, I'm happy, despite inconsistencies! :) 👍

**Comment by SteveAmor** [comment]
Agreed on the copy but the formatting looks poor for PR #2 as ..... (press **Ctrl + Alt + t**): is split across two lines:

https://www.raspberrypi.org/learning/using-scratch2/requirements/software/

Just my OCD kicking in :-)
